/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveIcon: typeof import('./src/components/ActiveIcon.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    DividerLine: typeof import('./src/components/DividerLine.vue')['default']
    HeroChip: typeof import('./src/components/HeroChip.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    IHeroiconsSolidMapPin: typeof import('~icons/heroicons-solid/map-pin')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TerminalBar: typeof import('./src/components/TerminalBar.vue')['default']
  }
}
